name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_SHA: ${{ github.sha }}
      CLIENT_ENVIRONMENT: production
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag bradmccoydev/kcd-website:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'bradmccoydev/kcd-website:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Docker Push
        run: docker push bradmccoydev/kcd-website:${{ github.sha }}
      
      - name: update tag for oc-web image on deployment
        run: |-
          export GITHUB_SHA=${{ github.sha }}
          find "chart" -name "*.tmpl" -exec bash -c 'envsubst < $1 > chart/${{ env.CLIENT_ENVIRONMENT }}-values.yaml' _ {} \;
          ls chart/
          cat chart/${{ env.CLIENT_ENVIRONMENT }}-values.yaml
          git status   
          git config --global user.email "github_actions@kcd-australia.io"
          git config --global user.name "github_actions"
          git add chart/${{ env.CLIENT_ENVIRONMENT }}-values.yaml
          echo $IMAGE_TAG
          git commit -m "update image tag with $GITHUB_SHA"
          git push
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
