name: CI

on:
  push:
    branches: [ feature/9/add-helm-releaser-action ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_SHA: ${{ github.sha }}
      CLIENT_ENVIRONMENT: production
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: update tag for kcd-ui image on deployment
        run: |-
          cd chart
          export GITHUB_SHA=${{ github.sha }}
          find "kcd-ui" -name "*.tmpl" -exec bash -c 'envsubst < $1 > kcd-ui/values.yaml' _ {} \;
          ls kcd-ui/
          cat kcd-ui/values.yaml
          git status   
          git add kcd-ui/values.yaml
          git commit -m "update image tag with $GITHUB_SHA"
          git push
      
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: chart
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
